import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material";
import theme from "@/theme";
import CssBaseline from "@mui/material/CssBaseline";
import ReactQueryProvider from "@/provider/ReactQueryProvider";
import { ToastContainer } from "react-toastify";
import { NotistackProvider } from "@/provider/NotiStackProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <ReactQueryProvider>
              <NotistackProvider
                anchorOrigin={{ horizontal: "right", vertical: "top" }}
              >
                <CssBaseline />

                {children}
              </NotistackProvider>
            </ReactQueryProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
